#!/bin/bash

set -e

ROLE_ID=$1
SECRET_ID=$2
ROLE=$3

usage() {
  echo "Usage:"
  echo "  read-secret ROLE_ID SECRET_ID ROLE[/KEY]"
  exit -1
}

[ -n "$ROLE_ID" ] || usage
[ -n "$SECRET_ID" ] || usage
[ -n "$ROLE" ] || usage

TOKEN=$(vault write auth/approle/login role_id=$ROLE_ID secret_id=$SECRET_ID -format=json | jq -r .auth.client_token)

vault login $TOKEN >/dev/null

vault read kv/$ROLE -format=json | jq -r '.data.json' | jq .
