#!/bin/bash

set -e

TOKEN=$1
ROLE=$2

usage() {
  echo "Usage:"
  echo "  write-secret TOKEN|- ROLE[/KEY] <JSON_FILE"
  exit -1
}

[ -n "$TOKEN" ] || usage
[ -n "$ROLE" ] || usage

[ "$TOKEN" == "-" ] || vault login $TOKEN >/dev/null

vault write kv/$ROLE json=-
